name: flutter_file_utils
description: Helper tools for managing files on Android
version: 0.1.0
homepage: https://github.com/kw2019ltd/flutter_file_utils

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.6.4
  path_provider: ^1.6.7
  package_info: ^0.4.0+17

dev_dependencies:
  pedantic: ^1.9.0

flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
